# Generated by Django 4.1.1 on 2023-02-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='img',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
